//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesForClass.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamesForClass.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AANI
        ///AARU
        ///ABAC
        ///ABAS
        ///ABBA
        ///ABBY
        ///ABED
        ///ABEL
        ///ABET
        ///ABEY
        ///ABIE
        ///ABIR
        ///ABLE
        ///ABLY
        ///ABOX
        ///ABSI
        ///ABUT
        ///ACCA
        ///ACER
        ///ACHE
        ///ACHY
        ///ACID
        ///ACIS
        ///ACLE
        ///ACME
        ///ACNE
        ///ACOR
        ///ACRE
        ///ACTA
        ///ACTS
        ///ACTU
        ///ACYL
        ///ADAD
        ///ADAD
        ///ADAI
        ///ADAM
        ///ADAR
        ///ADAT
        ///ADAW
        ///ADAY
        ///ADDA
        ///ADDA
        ///ADDU
        ///ADDY
        ///ADET
        ///ADIB
        ///ADIN
        ///ADIT
        ///ADMI
        ///ADRY
        ///ADZE
        ///AEON
        ///AERO
        ///AERY
        ///AFAR
        ///AFAR
        ///AFFA
        ///AFFY
        ///AGAG
        ///AGAL
        ///AGAO
        ///AGAR
        ///AGAU
        ///AGAZ
        ///AGED
        ///AGEE
        ///AGEN
        ///AGER
        ///AGHA
        ///AGIB
        ///AGIO
        ///AGLA
        ///AGOG
        ///AGON
        ///AGRA
        ///AGRE
        ///AGUA
        ///AGUE
        ///AHEM
        ///AHET
        ///AHEY
        ///AHIR
        ///AHOM
        ///AHOY
        ///AHUM
        ///AIAS
        ///AIDE
        ///AIEL
        ///AILE
        ///AINT
        ///AINU
        ///AION
        ///AIRA
        ///AIRE
        ///AIRT
        ///AIRY
        ///AJAR
        ///AJOG
        ///AKAL
        ///AKAN
        ///AKEE
        ///AKEY
        ///AK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _4words {
            get {
                return ResourceManager.GetString("_4words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aback
        ///abase
        ///abate
        ///abbey
        ///abbot
        ///abhor
        ///abide
        ///abled
        ///abode
        ///abort
        ///about
        ///above
        ///abuse
        ///abyss
        ///acorn
        ///acrid
        ///actor
        ///acute
        ///adage
        ///adapt
        ///adept
        ///admin
        ///admit
        ///adobe
        ///adopt
        ///adore
        ///adorn
        ///adult
        ///affix
        ///afire
        ///afoot
        ///afoul
        ///after
        ///again
        ///agape
        ///agate
        ///agent
        ///agile
        ///aging
        ///aglow
        ///agony
        ///agora
        ///agree
        ///ahead
        ///aider
        ///aisle
        ///alarm
        ///album
        ///alert
        ///algae
        ///alibi
        ///alien
        ///align
        ///alike
        ///alive
        ///allay
        ///alley
        ///allot
        ///allow
        ///alloy
        ///aloft
        ///alone
        ///along
        ///aloof
        ///aloud
        ///alpha
        ///altar
        ///alter
        ///amass
        ///amaze
        ///amber
        ///amble
        ///amend
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _5words {
            get {
                return ResourceManager.GetString("_5words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aahing
        ///aaliis
        ///aarrgh
        ///abacas
        ///abacus
        ///abakas
        ///abamps
        ///abased
        ///abaser
        ///abases
        ///abasia
        ///abated
        ///abater
        ///abates
        ///abatis
        ///abator
        ///abayas
        ///abbacy
        ///abbess
        ///abbeys
        ///abbots
        ///abduce
        ///abduct
        ///abeles
        ///abelia
        ///abhors
        ///abided
        ///abider
        ///abides
        ///abject
        ///abjure
        ///ablate
        ///ablaut
        ///ablaze
        ///ablest
        ///ablins
        ///abloom
        ///ablush
        ///abmhos
        ///aboard
        ///aboded
        ///abodes
        ///abohms
        ///abolla
        ///abomas
        ///aboral
        ///aborts
        ///abound
        ///aboves
        ///abrade
        ///abroad
        ///abrupt
        ///abseil
        ///absent
        ///absorb
        ///absurd
        ///abulia
        ///abulic
        ///abused
        ///abuser
        ///abuses
        ///abvolt
        ///abwatt
        ///abying
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _6words {
            get {
                return ResourceManager.GetString("_6words", resourceCulture);
            }
        }
    }
}
